export const enCourse = {
  title: "Courses",
  createCourse: "Create course",
  description:
    "On this page you can tune requisites of the course and save them. For more details, please read the Training Process Management Manual.",
  generalInformation: "General Information",
  courseCode: "Course Code",
  active: "Active",
  courseTitle: "Course Title",
  trainingProvider: "Training Provider",
  section: "Section",
  deliveryType: "DeliveryType",
  category: "Category",
  language: "Language",
  prerequisites: "Prerequisites",
  duration: "Duration",
  objective: "Objective",
  hour: "h.",
  minute: "m.",
  targetAudience: "Target Audience",
  courseDescription: "Course Description",
  content: "Content",
  certification: "Certification",
  validityPeriod: "Validity Period",
  months: "months",
  additionalInformation: "Additional Information",
  owner: "Owner",
  enrollmentPeriod: "Enrollment Period",
  days: "days",
  numberOfStudents: "Number of students",
  min: "min",
  max: "max",
  preliminaryLogistics: "Preliminary Logistics",
  typeOfAssessment: "Type of Assessment",
  save: "Save",
  cancel: "Cancel",
  requiredFieldMsg: "This is a required field",
  codeRequired: "Code required",
  trainingProviderRequired: "Training provider required",
  sectionRequired: "Section required",
  deliveryRequired: "Delivery type required"
};
